    apiVersion: flink.apache.org/v1beta1
    kind: FlinkDeployment
    metadata:
      name: emr-on-eks-java-app
    spec:
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
        state.checkpoints.dir: s3://emr-eks-workshop-744527726443/flink-eks/checkpoints/
        state.savepoints.dir: s3://emr-eks-workshop-744527726443/flink-eks/savepoints/
        kubernetes.jobmanager.node-selector: nodePool:default
        kubernetes.taskmanager.node-selector: nodePool:default
        kubernetes.operator.job.autoscaler.enabled: true
        kubernetes.operator.job.autoscaler.stabilization.interval: 1m
        kubernetes.operator.job.autoscaler.metrics.window: 5m
        kubernetes.operator.job.autoscaler.target.utilization: 0.6
        kubernetes.operator.job.autoscaler.target.utilization.boundary: 0.2
        kubernetes.operator.job.autoscaler.restart.time: 2m
        kubernetes.operator.job.autoscaler.catch-up.duration: 5m
      flinkVersion: v1_18
      executionRoleArn: arn:aws:iam::744527726443:role/emr-flink-lab-role
      emrReleaseLabel: "emr-7.0.0-flink-latest"
      image: 744527726443.dkr.ecr.us-east-1.amazonaws.com/eks-flink:emr-7.0.0-java-2.3
      jobManager:
        storageDir: s3://emr-eks-workshop-744527726443/flink-eks/ha/
        resource:
          memory: "2048m"
          cpu: 1
      taskManager:
        resource:
          memory: "2048m"
          cpu: 1
      job:
        # if you have your job jar in S3 bucket you can use that path as well
        jarURI: local:///usr/lib/flink/userlib/emr-eks-flink-java-1.0.9.jar
        entryClass: com.amazonaws.emr.flink.S3StreamingParquetSinkJob
        args:
            - ExampleInputStream
            - us-east-1
            - s3://emr-eks-workshop-744527726443/flink-data/s3_sink_agg_1min/
        parallelism: 2
        upgradeMode: savepoint
        savepointTriggerNonce: 0
      monitoringConfiguration:
        cloudWatchMonitoringConfiguration:
          logGroupName: /aws/emr-eks/flink
