FROM public.ecr.aws/emr-on-eks/flink/emr-7.9.0-flink:latest

ARG MAVEN_URL=https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
ARG VERSION=1.0.0

USER root

ADD pom.xml /tmp/pom.xml

RUN yum install -y wget tar \
 && mkdir -p /usr/share/maven \
 && curl -o /tmp/apache-maven.tar.gz ${MAVEN_URL} \
 && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
 && rm -f /tmp/apache-maven.tar.gz  \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
 && cd /tmp && mvn clean install -f pom.xml \
 && mkdir -p /opt/flink/plugins/pyflink-uber-jar \
 && cp target/pyflink-uber-jar-${VERSION}.jar /opt/flink/plugins/pyflink-uber-jar/pyflink-uber-jar-${VERSION}.jar

USER flink:flink